export const data = [
   { id: 1, name: "Alice" },
   { id: 2, name: "Bob" },
   { id: 3, name: "Charlie" },
   { id: 4, name: "David" },
   { id: 5, name: "Eva" },
   { id: 6, name: "Frank" },
   { id: 7, name: "Grace" },
   { id: 8, name: "Hannah" },
   { id: 9, name: "Isaac" },
   { id: 10, name: "Jack" },
   { id: 11, name: "Kathy" },
   { id: 12, name: "Leo" },
   { id: 13, name: "Mia" },
   { id: 14, name: "Nina" },
   { id: 15, name: "Oscar" },
   { id: 16, name: "Paul" },
   { id: 17, name: "Quinn" },
   { id: 18, name: "Rita" },
   { id: 19, name: "Sam" },
   { id: 20, name: "Tina" },
   { id: 21, name: "Uma" },
   { id: 22, name: "Victor" },
   { id: 23, name: "Wendy" },
   { id: 24, name: "Xander" },
   { id: 25, name: "Yara" },
   { id: 26, name: "Zane" },
   { id: 27, name: "Ava" },
   { id: 28, name: "Brian" },
   { id: 29, name: "Cathy" },
   { id: 30, name: "Derek" },
   { id: 31, name: "Ella" },
   { id: 32, name: "Felix" },
   { id: 33, name: "Gina" },
   { id: 34, name: "Henry" },
   { id: 35, name: "Ivy" },
   { id: 36, name: "Jake" },
   { id: 37, name: "Kira" },
   { id: 38, name: "Liam" },
   { id: 39, name: "Maya" },
   { id: 40, name: "Nate" },
   { id: 41, name: "Olivia" },
   { id: 42, name: "Penny" },
   { id: 43, name: "Quincy" },
   { id: 44, name: "Ralph" },
   { id: 45, name: "Sophie" },
   { id: 46, name: "Tommy" },
   { id: 47, " name": "Ulysses" },
   { id: 48, name: "Vera" },
   { id: 49, name: "Walter" },
   { id: 50, name: "Xena" },
   { id: 51, name: "Yosef" },
   { id: 52, name: "Zelda" },
   { id: 53, name: "Anya" },
   { id: 54, name: "Boris" },
   { id: 55, name: "Clara" },
   { id: 56, name: "Dante" },
   { id: 57, name: "Evelyn" },
   { id: 58, name: "Freya" },
   { id: 59, name: "Gideon" },
   { id: 60, name: "Hugo" },
   { id: 61, name: "Iris" },
   { id: 62, name: "Jasper" },
   { id: 63, name: "Kendall" },
   { id: 64, name: "Luna" },
   { id: 65, name: "Milo" },
   { id: 66, name: "Nola" },
   { id: 67, name: "Owen" },
   { id: 68, name: "Paige " },
   { id: 69, name: "Quinn " },
   { id: 70, name: "Riley " },
   { id: 71, name: "Sienna " },
   { id: 72, name: "Troy " },
   { id: 73, name: "Uriah " },
   { id: 74, name: "Violet " },
   { id: 75, name: "Wyatt " },
   { id: 76, name: "Ximena " },
   { id: 77, name: "Yasmin " },
   { id: 78, name: "Zara " },
   { id: 79, name: "Aiden " },
   { id: 80, name: "Brooke" },
   { id: 81, name: "Cameron" },
   { id: 82, name: "Delilah" },
   { id: 83, name: "Emmett" },
   { id: 84, name: "Fiona" },
   { id: 85, name: "Grayson" },
   { id: 86, name: "Hayley" },
   { id: 87, name: "Isaiah" },
   { id: 88, name: "Jade" },
   { id: 89, name: "Kendrick" },
   { id: 90, name: "Leah" },
   { id: 91, name: "Mason" },
   { id: 92, name: "Nicole" },
   { id: 93, name: "Oliver" },
   { id: 94, name: "Penelope" },
   { id: 95, name: "Quentin" },
   { id: 96, name: "Rachel" },
   { id: 97, name: "Sebastian" },
   { id: 98, name: "Tessa" },
   { id: 99, name: "Uriel" },
   { id: 100, name: "Vanessa" },
];
